-- Generated by supabase/scripts/build-seed.ts — do not edit by hand.
-- Image paths are relative; the API resolves them against its own origin (api/public/seed/).
begin;

insert into public.titles (id, title, year, type, poster_url, note, created_by) values
  ('hanggang-umaga', 'Hanggang Umaga', 2016, 'Movie', '/seed/titles/hanggang-umaga.png', null, null),
  ('alon-at-apoy', 'Alon at Apoy', 2019, 'Teleserye', '/seed/titles/alon-at-apoy.png', null, null),
  ('ang-huling-liham', 'Ang Huling Liham', 2021, 'Movie', '/seed/titles/ang-huling-liham.png', null, null),
  ('bituin-sa-maynila', 'Bituin sa Maynila', 2023, 'Teleserye', '/seed/titles/bituin-sa-maynila.png', 'Ep. 42 of 60', null),
  ('salamin', 'Salamin', 2025, 'Movie', '/seed/titles/salamin.png', 'Out Dec 25', null),
  ('gabi-ng-liwanag', 'Gabi ng Liwanag', 2022, 'Teleserye', '/seed/titles/gabi-ng-liwanag.png', 'Ep. 12 of 40', null),
  ('diwata', 'Diwata', 2018, 'Teleserye', '/seed/titles/diwata.png', null, null),
  ('tahanan', 'Tahanan', 2020, 'Movie', '/seed/titles/tahanan.png', null, null),
  ('kung-sakaling-ikaw', 'Kung Sakaling Ikaw', 2024, 'Movie', '/seed/titles/kung-sakaling-ikaw.png', null, null),
  ('bagsik', 'Bagsik', 2017, 'Movie', '/seed/titles/bagsik.png', null, null),
  ('pare-ko-pare-mo', 'Pare Ko, Pare Mo', 2019, 'Movie', '/seed/titles/pare-ko-pare-mo.png', null, null),
  ('ang-batang-tubig', 'Ang Batang Tubig', 2023, 'Movie', '/seed/titles/ang-batang-tubig.png', null, null),
  ('kalye-kings', 'Kalye Kings', 2024, 'Series', '/seed/titles/kalye-kings.png', 'Ep. 3 of 8', null),
  ('mga-anak-ng-bagyo', 'Mga Anak ng Bagyo', 1987, 'Movie', '/seed/titles/mga-anak-ng-bagyo.png', null, null),
  ('panahon-ng-tag-init', 'Panahon ng Tag-init', 1996, 'Teleserye', '/seed/titles/panahon-ng-tag-init.png', null, null),
  ('rebolusyon-1896', 'Rebolusyon 1896', 2005, 'Movie', '/seed/titles/rebolusyon-1896.png', null, null),
  ('sana-all', 'Sana All', 2024, 'Series', '/seed/titles/sana-all.png', null, null),
  ('bahay-ni-kuya-dindo', 'Bahay ni Kuya Dindo', 1998, 'Series', '/seed/titles/bahay-ni-kuya-dindo.png', null, null),
  ('biyaheng-langit', 'Biyaheng Langit', 2018, 'Movie', '/seed/titles/biyaheng-langit.png', null, null),
  ('tiyanak-trilogy', 'Tiyanak Trilogy', 2017, 'Movie', '/seed/titles/tiyanak-trilogy.png', null, null),
  ('hatinggabi', 'Hatinggabi', 2021, 'Series', '/seed/titles/hatinggabi.png', null, null),
  ('probinsyano-blues', 'Probinsyano Blues', 2022, 'Movie', '/seed/titles/probinsyano-blues.png', null, null),
  ('himig-ng-isla', 'Himig ng Isla', 2025, 'Movie', '/seed/titles/himig-ng-isla.png', null, null),
  ('tadhana-delivery', 'Tadhana Delivery', 2024, 'Series', '/seed/titles/tadhana-delivery.png', null, null),
  ('bantay-dagat', 'Bantay Dagat', 2020, 'Teleserye', '/seed/titles/bantay-dagat.png', null, null)
on conflict (id) do nothing;

insert into public.actors (id, name, stage_name, tagline, birthdate, hometown, network, agency, generation, gender, decades, genres, base_fans, bio, photo_url, socials, spotlight, trending_rank, created_by) values
  ('amihan-reyes', 'Amihan Reyes', 'Ang Reyna ng Drama', 'Box-office royalty with four Best Actress trophies', '1991-03-14', 'Iloilo City, Iloilo', 'ABS-CBN', 'Star Magic', 'Millennial', 'Female', array['2010s', '2020s']::text[], array['Drama', 'Romance']::text[], 12400000, 'Discovered at sixteen in a mall talent search in Iloilo, Amihan Reyes spent five years in supporting roles before "Hanggang Umaga" turned her into the most bankable dramatic lead of her generation. Critics point to her stillness — long, unblinking takes that carry an entire scene without dialogue. She now splits her time between primetime teleseryes and independent films, and produces two of them a year through her own outfit, Habagat Pictures.', '/seed/actors/amihan-reyes.png', '{"instagram":"@amihanreyes","x":"@amihanreyes","tiktok":"@amihan"}'::jsonb, true, 4, null),
  ('liway-santillan', 'Liwayway Santillan', 'Liway', 'Kapuso primetime lead and 2024 Gawad Sining honoree', '1993-08-02', 'Lipa, Batangas', 'GMA', 'Sparkle GMA Artist Center', 'Millennial', 'Female', array['2010s', '2020s']::text[], array['Drama', 'Fantasy', 'Romance']::text[], 8900000, 'Liway came up through fantaseryes, where she learned to sell the impossible with a straight face — and then spent the next decade proving she could do the same with ordinary heartbreak. Her turn as a working mother in "Gabi ng Liwanag" was the highest-rated Kapuso finale in six years. Offscreen she runs a scholarship fund for public-school drama students in Batangas.', '/seed/actors/liway-santillan.png', '{"instagram":"@liwaysantillan","tiktok":"@liway"}'::jsonb, false, 2, null),
  ('manny-dalisay', 'Emmanuel Dalisay', 'Manny D', 'Action-comedy lead turned indie-film favorite', '1990-11-28', 'Cebu City, Cebu', 'Viva', 'Viva Artists Agency', 'Millennial', 'Male', array['2010s', '2020s']::text[], array['Action', 'Comedy', 'Drama']::text[], 6200000, 'Manny Dalisay started as a stuntman on Viva action pictures and still does most of his own falls. His comic timing was an accident — a director kept the improvised takes — and it made him the rare Filipino leading man who opens both an action tentpole and a two-hander shot on a single Cebu street. He is unusually protective of his rest days and has spoken publicly about set safety.', '/seed/actors/manny-dalisay.png', '{"instagram":"@mannydalisay","x":"@mannyd"}'::jsonb, true, null, null),
  ('charing-villanueva', 'Rosario Villanueva', 'Tita Charing', 'Five decades on screen, and the Kapamilya matriarch of them all', '1961-06-09', 'Vigan, Ilocos Sur', 'ABS-CBN', 'Star Magic', 'Legends', 'Female', array['1980s', '1990s', '2000s', '2010s', '2020s']::text[], array['Drama', 'Period', 'Comedy']::text[], 4100000, 'Rosario "Charing" Villanueva made her first film in 1979 and has not gone a year without a credit since. She is the industry''s reigning matriarch — the mother, the lola, the judge — and the person younger actors quote when asked about discipline. Her one-take monologue in "Ang Huling Liham" is taught in film schools. She was named a National Artist nominee for Film in 2024.', '/seed/actors/charing-villanueva.png', '{"instagram":"@titacharing"}'::jsonb, true, null, null),
  ('nanding-aguilar', 'Fernando Aguilar', 'Nanding', 'The Kapuso character actor who steals every scene', '1959-01-22', 'Malolos, Bulacan', 'GMA', 'GMA Artist Center', 'Legends', 'Male', array['1980s', '1990s', '2000s', '2010s', '2020s']::text[], array['Drama', 'Period', 'Action']::text[], 2700000, 'A stage actor first, Fernando Aguilar spent the eighties in Bulacan community theater before television found him. He has played the father, the villain, the priest and the president — often in the same season — and remains the industry''s most requested table-read partner for young leads. He teaches a free Saturday acting workshop in Malolos that has run for nineteen years.', '/seed/actors/nanding-aguilar.png', '{"instagram":"@nandingaguilar","x":"@nandinga"}'::jsonb, false, 5, null),
  ('bibi-manalo', 'Bianca Manalo', 'Bibi', 'The Gen Z breakout with 3.2M in eight months', '2003-02-17', 'Davao City, Davao del Sur', 'ABS-CBN', 'Star Magic', 'Gen Z', 'Female', array['2020s']::text[], array['Romance', 'Comedy', 'Drama']::text[], 3200000, 'Bibi Manalo posted a two-minute monologue from her Davao bedroom in 2024; it was reposted by a casting director and she was on a Star Magic set within the month. She has since carried a streaming romance and a horror anthology episode, and is the youngest actress ever shortlisted for a Gawad Urian acting nod. She still edits her own vlogs.', '/seed/actors/bibi-manalo.png', '{"instagram":"@bibimanalo","tiktok":"@bibi"}'::jsonb, false, 1, null),
  ('rafa-ocampo', 'Rafael Ocampo', 'Rafa', 'Sparkle''s young leading man and reluctant heartthrob', '2001-09-05', 'Baguio City, Benguet', 'GMA', 'Sparkle GMA Artist Center', 'Gen Z', 'Male', array['2020s']::text[], array['Romance', 'Comedy', 'Action']::text[], 2900000, 'Rafa Ocampo was a competitive swimmer in Baguio until a shampoo commercial changed the plan. Three years in, he has learned to lean away from the heartthrob framing — his best work so far is a quiet, unglamorous turn as a delivery rider in "Kalye Kings". He is currently studying film production between shoots.', '/seed/actors/rafa-ocampo.png', '{"instagram":"@rafaocampo","tiktok":"@rafa"}'::jsonb, false, 3, null),
  ('dindo-salazar', 'Rodolfo Salazar', 'Dindo', 'The Kapatid comedy king who never misses a punchline', '1965-04-30', 'San Fernando, Pampanga', 'TV5', 'Cornerstone Talents', 'Legends', 'Male', array['1980s', '1990s', '2000s', '2010s', '2020s']::text[], array['Comedy', 'Drama']::text[], 3800000, 'Dindo Salazar started out doing impressions at Pampanga fiestas and hasn''t stopped making the country laugh since. His Sunday sitcom "Bahay ni Kuya Dindo" ran for eleven seasons, and his late-career dramatic turn as a grieving jeepney driver surprised critics who had only seen the clown. He still writes his own material and tests every joke on his grandchildren first.', '/seed/actors/dindo-salazar.png', '{"instagram":"@dindosalazar","x":"@kuyadindo"}'::jsonb, false, null, null),
  ('isay-dimaculangan', 'Maria Luisa Dimaculangan', 'Isay', 'Queen of Pinoy horror with a scream heard nationwide', '1992-10-31', 'Legazpi City, Albay', 'TV5', 'Cornerstone Talents', 'Millennial', 'Female', array['2010s', '2020s']::text[], array['Horror', 'Drama', 'Fantasy']::text[], 5100000, 'Isay Dimaculangan grew up on her lola''s aswang stories in the shadow of Mayon, and she brings that folklore to every role. Her "Tiyanak Trilogy" is the most-watched Filipino horror franchise on streaming, and she insists on doing her own underwater scenes. Between frights she hosts a podcast on Bicolano myths.', '/seed/actors/isay-dimaculangan.png', '{"instagram":"@isaydimaculangan","tiktok":"@isayscreams"}'::jsonb, true, null, null),
  ('kaloy-mendoza', 'Carlos Mendoza', 'Kaloy', 'Indie cinema''s quiet storm from Tacloban', '2000-12-08', 'Tacloban City, Leyte', 'Independent', 'Habagat Pictures', 'Gen Z', 'Male', array['2020s']::text[], array['Drama', 'Period']::text[], 1400000, 'Kaloy Mendoza was thirteen when Typhoon Yolanda flattened his neighborhood; a decade later he played a survivor in "Ang Batang Tubig" and made grown critics cry at Cinemalaya. He works almost exclusively in independent film, chooses projects by script alone, and has turned down two primetime teleserye offers to stay in Leyte with his family.', '/seed/actors/kaloy-mendoza.png', '{"instagram":"@kaloymendoza"}'::jsonb, false, 8, null),
  ('ligaya-tan', 'Ligaya Tan', 'Gaya', 'Viva''s rom-com sweetheart from Zamboanga', '2002-05-21', 'Zamboanga City, Zamboanga del Sur', 'Viva', 'Viva Artists Agency', 'Gen Z', 'Female', array['2020s']::text[], array['Romance', 'Comedy']::text[], 4600000, 'Gaya Tan sings, dances and speaks four languages — Chavacano, Tagalog, English and Hokkien — and uses all of them on set. Her streaming rom-com "Tadhana Delivery" topped the local charts for nine weeks. She is known for learning every crew member''s name by the second shooting day.', '/seed/actors/ligaya-tan.png', '{"instagram":"@ligayatan","tiktok":"@gaya"}'::jsonb, false, 6, null),
  ('ramon-estrella', 'Ramon Estrella', 'Mon', 'Kapamilya action star who trained with the Coast Guard', '1988-07-12', 'Cagayan de Oro, Misamis Oriental', 'ABS-CBN', 'Star Magic', 'Millennial', 'Male', array['2010s', '2020s']::text[], array['Action', 'Drama']::text[], 7300000, 'Mon Estrella spent six months with the Philippine Coast Guard preparing for "Bantay Dagat" and came out a certified rescue swimmer. The series made him primetime''s most reliable action lead, but his favorite role is the soft-spoken father in the family drama "Tahanan". He runs a free swimming clinic for kids every summer in Cagayan de Oro.', '/seed/actors/ramon-estrella.png', '{"instagram":"@monestrella","x":"@monestrella"}'::jsonb, false, 7, null)
on conflict (id) do nothing;

insert into public.credits (actor_id, title_id, role, position) values
  ('amihan-reyes', 'hanggang-umaga', 'Teresa', 0),
  ('amihan-reyes', 'alon-at-apoy', 'Marisol Benitez', 1),
  ('amihan-reyes', 'ang-huling-liham', 'Elena', 2),
  ('amihan-reyes', 'bituin-sa-maynila', 'Dra. Paz Alcantara', 3),
  ('amihan-reyes', 'salamin', 'Nora', 4),
  ('liway-santillan', 'gabi-ng-liwanag', 'Amparo', 0),
  ('liway-santillan', 'diwata', 'Diwata Maghari', 1),
  ('liway-santillan', 'tahanan', 'Sister Cecilia', 2),
  ('liway-santillan', 'kung-sakaling-ikaw', 'Rina', 3),
  ('manny-dalisay', 'bagsik', 'Sgt. Dante Rivas', 0),
  ('manny-dalisay', 'pare-ko-pare-mo', 'Boyet', 1),
  ('manny-dalisay', 'ang-batang-tubig', 'Berto', 2),
  ('manny-dalisay', 'kalye-kings', 'Andres', 3),
  ('charing-villanueva', 'mga-anak-ng-bagyo', 'Lourdes', 0),
  ('charing-villanueva', 'panahon-ng-tag-init', 'Aling Feling', 1),
  ('charing-villanueva', 'ang-huling-liham', 'Nanay Charing', 2),
  ('charing-villanueva', 'bituin-sa-maynila', 'Doña Pilar', 3),
  ('nanding-aguilar', 'alon-at-apoy', 'Don Emilio', 0),
  ('nanding-aguilar', 'rebolusyon-1896', 'Heneral Basa', 1),
  ('nanding-aguilar', 'gabi-ng-liwanag', 'Tatay Berting', 2),
  ('nanding-aguilar', 'salamin', 'Mang Ponso', 3),
  ('bibi-manalo', 'sana-all', 'Yumi', 0),
  ('bibi-manalo', 'kung-sakaling-ikaw', 'Jamie', 1),
  ('bibi-manalo', 'salamin', 'Young Nora', 2),
  ('rafa-ocampo', 'kalye-kings', 'Nico', 0),
  ('rafa-ocampo', 'sana-all', 'Migs', 1),
  ('rafa-ocampo', 'bituin-sa-maynila', 'Julio', 2),
  ('dindo-salazar', 'bahay-ni-kuya-dindo', 'Kuya Dindo', 0),
  ('dindo-salazar', 'biyaheng-langit', 'Mang Isko', 1),
  ('dindo-salazar', 'pare-ko-pare-mo', 'Tito Bong', 2),
  ('isay-dimaculangan', 'tiyanak-trilogy', 'Celeste', 0),
  ('isay-dimaculangan', 'hatinggabi', 'Nurse Lorna', 1),
  ('isay-dimaculangan', 'alon-at-apoy', 'Isadora', 2),
  ('kaloy-mendoza', 'ang-batang-tubig', 'Junjun', 0),
  ('kaloy-mendoza', 'probinsyano-blues', 'Dodong', 1),
  ('kaloy-mendoza', 'himig-ng-isla', 'Elias', 2),
  ('ligaya-tan', 'tadhana-delivery', 'Joy', 0),
  ('ligaya-tan', 'kung-sakaling-ikaw', 'Bea', 1),
  ('ligaya-tan', 'sana-all', 'Pia', 2),
  ('ramon-estrella', 'bantay-dagat', 'Lt. Gabriel Cruz', 0),
  ('ramon-estrella', 'tahanan', 'Jose', 1),
  ('ramon-estrella', 'bagsik', 'Officer Lando', 2),
  ('ramon-estrella', 'bituin-sa-maynila', 'Dr. Marco Alcantara', 3);

insert into public.awards (actor_id, title, org, year, won, position) values
  ('amihan-reyes', 'Best Actress', 'Gawad Urian', 2022, true, 0),
  ('amihan-reyes', 'Best Actress', 'Metro Manila Film Festival', 2021, true, 1),
  ('amihan-reyes', 'Best Drama Actress', 'PMPC Star Awards for TV', 2020, true, 2),
  ('amihan-reyes', 'Best Actress', 'FAMAS Awards', 2019, false, 3),
  ('liway-santillan', 'Best Actress', 'Gawad Sining', 2024, true, 0),
  ('liway-santillan', 'Best Primetime Actress', 'PMPC Star Awards for TV', 2023, true, 1),
  ('liway-santillan', 'Movie Actress of the Year', 'GMMSF Box-Office Entertainment', 2021, false, 2),
  ('manny-dalisay', 'Best Actor', 'Cinemalaya', 2023, true, 0),
  ('manny-dalisay', 'Best Actor', 'FAMAS Awards', 2024, false, 1),
  ('charing-villanueva', 'Lifetime Achievement', 'FAMAS Awards', 2023, true, 0),
  ('charing-villanueva', 'Best Supporting Actress', 'Gawad Urian', 2021, true, 1),
  ('charing-villanueva', 'Best Actress', 'Metro Manila Film Festival', 1996, true, 2),
  ('nanding-aguilar', 'Best Supporting Actor', 'Gawad Urian', 2020, true, 0),
  ('nanding-aguilar', 'Best Single Performance', 'PMPC Star Awards for TV', 2015, true, 1),
  ('bibi-manalo', 'Breakthrough Performance', 'Gawad Sining', 2025, true, 0),
  ('bibi-manalo', 'Best Actress', 'Gawad Urian', 2025, false, 1),
  ('rafa-ocampo', 'Male Star of the Night', 'Sparkle Gala', 2025, true, 0),
  ('dindo-salazar', 'Best Comedy Actor', 'PMPC Star Awards for TV', 2004, true, 0),
  ('dindo-salazar', 'Best Actor', 'Metro Manila Film Festival', 2018, true, 1),
  ('isay-dimaculangan', 'Best Actress', 'Cinemalaya', 2021, true, 0),
  ('isay-dimaculangan', 'Best Actress', 'FAMAS Awards', 2022, false, 1),
  ('kaloy-mendoza', 'Best Actor', 'Gawad Urian', 2024, true, 0),
  ('kaloy-mendoza', 'Breakthrough Performance', 'Gawad Sining', 2023, true, 1),
  ('ligaya-tan', 'New Movie Actress of the Year', 'PMPC Star Awards for Movies', 2025, true, 0),
  ('ramon-estrella', 'Best Drama Actor', 'PMPC Star Awards for TV', 2021, true, 0),
  ('ramon-estrella', 'Best Actor', 'Metro Manila Film Festival', 2020, false, 1);

insert into public.news (id, headline, excerpt, body, source, minutes_read, published_at, image_url, tag, actor_id) values
  ('n1', 'Amihan Reyes takes home her fourth Best Actress trophy', 'The "Salamin" star swept the acting field at last night''s Gawad Sining, dedicating the win to her late acting coach in Iloilo.', 'Amihan Reyes walked into the Gawad Sining ballroom as the favorite and left with the night''s biggest prize, her fourth Best Actress trophy in six years.

In a short, tearful speech she thanked her late acting coach from Iloilo, who first taught her to "let the silence do the work." "Salamin" also won Best Picture and Best Screenplay, making it the most awarded film of the season.', 'Showbiz Weekly', 4, now() - interval '2 hours', '/seed/news/n1.png', 'Awards', 'amihan-reyes'),
  ('n2', '"Kalye Kings" renewed for a second season', 'Production moves to Cebu in January with Manny Dalisay and Rafa Ocampo both returning.', 'The street-racing drama "Kalye Kings" has been renewed for a second season after becoming the most-streamed local series of the year.

Production moves to Cebu in January. Manny Dalisay and Rafa Ocampo are both confirmed to return, and the showrunners promise "fewer cars, more heart" in the new episodes.', 'Kapuso Insider', 3, now() - interval '6 hours', '/seed/news/n2.png', 'Teleserye', 'manny-dalisay'),
  ('n3', 'Tita Charing named National Artist nominee for Film', 'Forty-six years and one hundred and twelve credits later, the industry matriarch gets her due.', 'Rosario "Tita Charing" Villanueva has been named a National Artist nominee for Film, capping a career of forty-six years and one hundred and twelve credits.

Colleagues across networks celebrated the news. Younger actors describe her as the industry''s conscience: first on set, last to leave, and never late with a line.', 'Sine Manila', 6, now() - interval '1 day', '/seed/news/n3.png', 'Legends', 'charing-villanueva'),
  ('n4', 'Bibi Manalo signs a two-picture deal with Habagat Pictures', 'The Gen Z breakout will lead a coming-of-age drama shot entirely in Davao next summer.', 'Bibi Manalo has signed a two-picture deal with Habagat Pictures, the production outfit founded by Amihan Reyes.

The first film is a coming-of-age drama to be shot entirely in Davao next summer. Manalo says she wants to show "the Davao I grew up in, not the postcard version."', 'Showbiz Weekly', 3, now() - interval '1 day', '/seed/news/n4.png', 'New Gen', 'bibi-manalo'),
  ('n5', 'Isay Dimaculangan confirms a fourth "Tiyanak" film', 'The horror queen says the new chapter will be shot entirely at night in the forests of Albay.', 'Isay Dimaculangan has confirmed that a fourth "Tiyanak" film is in development, with shooting scheduled at night in the forests around Mayon Volcano.

The actress, who is also a producer on the franchise, promises the scariest chapter yet and a deeper dive into Bicolano folklore.', 'Sine Manila', 3, now() - interval '2 days', '/seed/news/n5.png', 'Horror', 'isay-dimaculangan'),
  ('n6', 'Kaloy Mendoza''s "Himig ng Isla" opens Cinemalaya', 'The Tacloban-born actor returns to the festival that launched him, this time as a lead and co-writer.', '"Himig ng Isla", starring and co-written by Kaloy Mendoza, will open this year''s Cinemalaya festival.

The film follows a young fisherman who composes songs to remember the people his island lost. Mendoza calls it "a love letter to Leyte" and says every extra in the film is a local from Tacloban.', 'Indie Pinoy', 5, now() - interval '3 days', '/seed/news/n6.png', 'Indie', 'kaloy-mendoza')
on conflict (id) do nothing;

insert into public.trivia_questions (id, prompt, actor_id, choices, answer_index, fact, position) values
  ('q1', 'Four Best Actress trophies and counting. Who is she?', 'amihan-reyes', array['Amihan Reyes', 'Liwayway Santillan', 'Bianca Manalo', 'Rosario Villanueva']::text[], 0, 'Amihan was discovered at sixteen in an Iloilo mall talent search.', 0),
  ('q2', 'This Kapuso lead began in fantaseryes. Name her.', 'liway-santillan', array['Bianca Manalo', 'Liwayway Santillan', 'Amihan Reyes', 'Rosario Villanueva']::text[], 1, '"Gabi ng Liwanag" gave GMA its highest-rated finale in six years.', 1),
  ('q3', 'Former stuntman, now an indie-film favorite. Who?', 'manny-dalisay', array['Rafael Ocampo', 'Fernando Aguilar', 'Emmanuel Dalisay', 'Nico Bautista']::text[], 2, 'Manny still performs most of his own falls.', 2),
  ('q4', 'Forty-six years on screen without a single gap year.', 'charing-villanueva', array['Amihan Reyes', 'Pilar Domingo', 'Liwayway Santillan', 'Rosario Villanueva']::text[], 3, 'Tita Charing was nominated as National Artist for Film in 2024.', 3),
  ('q5', 'A Davao bedroom monologue made this star famous. Who?', 'bibi-manalo', array['Bianca Manalo', 'Amihan Reyes', 'Liwayway Santillan', 'Yumi Cruz']::text[], 0, 'Bibi is the youngest actress ever shortlisted for a Gawad Urian acting nod.', 4),
  ('q6', 'Baguio swimmer turned Sparkle leading man.', 'rafa-ocampo', array['Emmanuel Dalisay', 'Rafael Ocampo', 'Fernando Aguilar', 'Migs Reyes']::text[], 1, 'A shampoo commercial ended Rafa''s competitive swimming career.', 5),
  ('q7', 'Eleven seasons of Sunday sitcom laughs. Who is this Kapatid legend?', 'dindo-salazar', array['Fernando Aguilar', 'Rodolfo Salazar', 'Emmanuel Dalisay', 'Ramon Estrella']::text[], 1, 'Dindo tests every joke on his grandchildren before it airs.', 6),
  ('q8', 'This horror queen does her own underwater scenes. Name her.', 'isay-dimaculangan', array['Maria Luisa Dimaculangan', 'Ligaya Tan', 'Bianca Manalo', 'Liwayway Santillan']::text[], 0, 'Isay hosts a podcast about Bicolano myths between films.', 7),
  ('q9', 'Indie star who turned down primetime to stay in Leyte.', 'kaloy-mendoza', array['Rafael Ocampo', 'Ramon Estrella', 'Carlos Mendoza', 'Emmanuel Dalisay']::text[], 2, 'Kaloy won Best Actor at the Gawad Urian for "Ang Batang Tubig".', 8),
  ('q10', 'She speaks Chavacano, Tagalog, English and Hokkien on set.', 'ligaya-tan', array['Bianca Manalo', 'Amihan Reyes', 'Maria Luisa Dimaculangan', 'Ligaya Tan']::text[], 3, '"Tadhana Delivery" topped the local streaming charts for nine weeks.', 9),
  ('q11', 'Certified rescue swimmer and primetime action lead. Who?', 'ramon-estrella', array['Ramon Estrella', 'Rafael Ocampo', 'Rodolfo Salazar', 'Carlos Mendoza']::text[], 0, 'Mon trained with the Philippine Coast Guard for six months for "Bantay Dagat".', 10),
  ('q12', 'Bulacan theater veteran with a free Saturday acting workshop.', 'nanding-aguilar', array['Rodolfo Salazar', 'Emmanuel Dalisay', 'Fernando Aguilar', 'Ramon Estrella']::text[], 2, 'Nanding''s Malolos workshop has run every Saturday for nineteen years.', 11)
on conflict (id) do nothing;

commit;
