// Generates supabase/seed.sql from the prototype's hardcoded data plus extra-data.ts.
// Run from the repo root:  npx tsx supabase/scripts/build-seed.ts
import { writeFileSync } from 'node:fs';
import { actors, spotlightIds, trendingIds } from '../../prototype/src/data/actors';
import { news } from '../../prototype/src/data/news';
import { triviaQuestions } from '../../prototype/src/data/trivia';
import {
  extraActors, extraNews, extraSpotlight, extraTrending, extraTrivia,
  newsActor, newsBodies, triviaActor,
} from './extra-data';

const slugify = (v: string) => v.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');

const q = (v: string | null | undefined) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const arr = (v: string[]) => `array[${v.map(q).join(', ')}]::text[]`;
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const isoDate = (human: string) => {
  const d = new Date(`${human} 12:00:00`);
  if (Number.isNaN(d.getTime())) throw new Error(`Bad date: ${human}`);
  const mm = String(d.getMonth() + 1).padStart(2, '0');
  const dd = String(d.getDate()).padStart(2, '0');
  return `${d.getFullYear()}-${mm}-${dd}`;
};

const fans = (label: string) => {
  const m = /^([\d.]+)\s*([KM]?)$/i.exec(label.trim());
  if (!m) throw new Error(`Bad follower label: ${label}`);
  const mult = m[2].toUpperCase() === 'M' ? 1_000_000 : m[2].toUpperCase() === 'K' ? 1_000 : 1;
  return Math.round(parseFloat(m[1]) * mult);
};

const watchNotes: Record<string, string> = {
  'bituin-sa-maynila': 'Ep. 42 of 60',
  'kalye-kings': 'Ep. 3 of 8',
  salamin: 'Out Dec 25',
  'gabi-ng-liwanag': 'Ep. 12 of 40',
};

const agoToInterval: Record<string, string> = {
  '2h ago': '2 hours', '6h ago': '6 hours', Yesterday: '1 day', '2 days ago': '2 days', '3 days ago': '3 days',
};

const allActors = [...actors, ...extraActors];
const spotlight = [...spotlightIds, ...extraSpotlight];
const trending = [...trendingIds, ...extraTrending];

const out: string[] = [
  '-- Generated by supabase/scripts/build-seed.ts — do not edit by hand.',
  '-- Image paths are relative; the API resolves them against its own origin (api/public/seed/).',
  'begin;',
  '',
];

// Titles (one per unique production)
const titles = new Map<string, { title: string; year: number; type: string }>();
for (const a of allActors) for (const c of a.credits) {
  const id = slugify(c.title);
  if (!titles.has(id)) titles.set(id, { title: c.title, year: c.year, type: c.type });
}
out.push('insert into public.titles (id, title, year, type, poster_url, note, created_by) values');
out.push([...titles].map(([id, t]) =>
  `  (${q(id)}, ${q(t.title)}, ${t.year}, ${q(t.type)}, ${q(`/seed/titles/${id}.png`)}, ${q(watchNotes[id] ?? null)}, null)`,
).join(',\n') + '\non conflict (id) do nothing;\n');

// Actors
out.push('insert into public.actors (id, name, stage_name, tagline, birthdate, hometown, network, agency, generation, gender, decades, genres, base_fans, bio, photo_url, socials, spotlight, trending_rank, created_by) values');
out.push(allActors.map((a) => {
  const rank = trending.indexOf(a.id);
  return `  (${q(a.id)}, ${q(a.name)}, ${q(a.stageName)}, ${q(a.tagline)}, ${q(isoDate(a.birthdate))}, ${q(a.hometown)}, ${q(a.network)}, ${q(a.agency)}, ${q(a.generation)}, ${q(a.gender)}, ${arr(a.decades)}, ${arr(a.genres)}, ${fans(a.followers)}, ${q(a.bio)}, ${q(`/seed/actors/${a.id}.png`)}, ${json(a.socials)}, ${spotlight.includes(a.id)}, ${rank === -1 ? 'null' : rank + 1}, null)`;
}).join(',\n') + '\non conflict (id) do nothing;\n');

// Credits & awards
out.push('insert into public.credits (actor_id, title_id, role, position) values');
out.push(allActors.flatMap((a) => a.credits.map((c, i) =>
  `  (${q(a.id)}, ${q(slugify(c.title))}, ${q(c.role)}, ${i})`)).join(',\n') + ';\n');
out.push('insert into public.awards (actor_id, title, org, year, won, position) values');
out.push(allActors.flatMap((a) => a.awards.map((w, i) =>
  `  (${q(a.id)}, ${q(w.title)}, ${q(w.org)}, ${w.year}, ${w.won}, ${i})`)).join(',\n') + ';\n');

// News
out.push('insert into public.news (id, headline, excerpt, body, source, minutes_read, published_at, image_url, tag, actor_id) values');
out.push([...news, ...extraNews].map((n) =>
  `  (${q(n.id)}, ${q(n.headline)}, ${q(n.excerpt)}, ${q(newsBodies[n.id] ?? '')}, ${q(n.source)}, ${n.minutesRead}, now() - interval ${q(agoToInterval[n.publishedAgo] ?? '1 day')}, ${q(`/seed/news/${n.id}.png`)}, ${q(n.tag)}, ${q(newsActor[n.id] ?? null)})`,
).join(',\n') + '\non conflict (id) do nothing;\n');

// Trivia
out.push('insert into public.trivia_questions (id, prompt, actor_id, choices, answer_index, fact, position) values');
out.push([...triviaQuestions, ...extraTrivia].map((t, i) =>
  `  (${q(t.id)}, ${q(t.prompt)}, ${q(triviaActor[t.id])}, ${arr(t.choices)}, ${t.answerIndex}, ${q(t.fact)}, ${i})`,
).join(',\n') + '\non conflict (id) do nothing;\n');

out.push('commit;');
writeFileSync('supabase/seed.sql', out.join('\n') + '\n');

// Manifest for the art generator
writeFileSync('supabase/scripts/art-manifest.json', JSON.stringify({
  actors: allActors.map((a) => ({ id: a.id, name: a.name, gender: a.gender, generation: a.generation, network: a.network })),
  titles: [...titles].map(([id, t]) => ({ id, ...t })),
  news: [...news, ...extraNews].map((n) => ({ id: n.id, tag: n.tag, headline: n.headline })),
}, null, 2));

console.log(`seed.sql: ${allActors.length} actors, ${titles.size} titles, ${news.length + extraNews.length} news, ${triviaQuestions.length + extraTrivia.length} trivia`);
