// Generates supabase/seed.sql from real-data.ts + photo-credits.json.
// Run from the repo root:  npx tsx supabase/scripts/build-seed.ts
import { readFileSync, writeFileSync } from 'node:fs';
import { realActors, realFeatures, realSpotlight, realTrending, realTrivia } from './real-data';

interface PhotoCredit { wikiTitle: string; artist: string; license: string; page: string; ext: string }
const photos: Record<string, PhotoCredit> = JSON.parse(readFileSync('supabase/scripts/photo-credits.json', 'utf8'));

const slugify = (v: string) => v.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const q = (v: string | null | undefined) => (v == null ? 'null' : `'${v.replace(/'/g, "''")}'`);
const arr = (v: string[]) => `array[${v.map(q).join(', ')}]::text[]`;

const out: string[] = [
  '-- Generated by supabase/scripts/build-seed.ts — do not edit by hand.',
  '-- Image paths are relative; the API resolves them against its own origin (api/public/seed/).',
  '-- Actor photos: Wikimedia Commons (credits in photo_credit / photo_source); facts from Wikipedia.',
  'begin;',
  '',
];

// Titles (one per unique production; the first credit's year wins)
const titles = new Map<string, { title: string; year: number; type: string }>();
for (const a of realActors) for (const c of a.credits) {
  const id = slugify(c.title);
  if (!titles.has(id)) titles.set(id, { title: c.title, year: c.year, type: c.type });
}
out.push('insert into public.titles (id, title, year, type, poster_url, note, created_by) values');
out.push([...titles].map(([id, t]) =>
  `  (${q(id)}, ${q(t.title)}, ${t.year}, ${q(t.type)}, ${q(`/seed/titles/${id}.png`)}, null, null)`,
).join(',\n') + '\non conflict (id) do nothing;\n');

// Actors
out.push('insert into public.actors (id, name, stage_name, tagline, birthdate, hometown, network, agency, generation, gender, decades, genres, base_fans, bio, photo_url, photo_credit, photo_source, wiki_title, socials, spotlight, trending_rank, created_by) values');
out.push(realActors.map((a) => {
  const p = photos[a.id];
  if (!p) throw new Error(`No photo credit for ${a.id}`);
  const rank = realTrending.indexOf(a.id);
  const credit = `${p.artist} · ${p.license} · Wikimedia Commons (cropped)`.slice(0, 300);
  return `  (${q(a.id)}, ${q(a.name)}, ${q(a.stageName)}, ${q(a.tagline)}, ${q(a.birthdate)}, ${q(a.hometown)}, ${q(a.network)}, ${q(a.agency)}, ${q(a.generation)}, ${q(a.gender)}, ${arr(a.decades)}, ${arr(a.genres)}, 0, ${q(a.bio)}, ${q(`/seed/actors/${a.id}.${p.ext}`)}, ${q(credit)}, ${q(p.page)}, ${q(p.wikiTitle)}, '{}'::jsonb, ${realSpotlight.includes(a.id)}, ${rank === -1 ? 'null' : rank + 1}, null)`;
}).join(',\n') + '\non conflict (id) do nothing;\n');

// Credits & awards
out.push('insert into public.credits (actor_id, title_id, role, position) values');
out.push(realActors.flatMap((a) => a.credits.map((c, i) =>
  `  (${q(a.id)}, ${q(slugify(c.title))}, ${q(c.role)}, ${i})`)).join(',\n') + ';\n');
out.push('insert into public.awards (actor_id, title, org, year, won, position) values');
out.push(realActors.flatMap((a) => a.awards.map((w, i) =>
  `  (${q(a.id)}, ${q(w.title)}, ${q(w.org)}, ${w.year}, ${w.won}, ${i})`)).join(',\n') + ';\n');

// Features (shown in the News section)
out.push('insert into public.news (id, headline, excerpt, body, source, minutes_read, published_at, image_url, tag, actor_id) values');
out.push(realFeatures.map((n) =>
  `  (${q(n.id)}, ${q(n.headline)}, ${q(n.excerpt)}, ${q(n.body)}, 'PinoyStars Features', ${n.minutesRead}, now() - interval ${q(n.ago)}, ${q(`/seed/news/${n.id}.png`)}, ${q(n.tag)}, ${q(n.actorId)})`,
).join(',\n') + '\non conflict (id) do nothing;\n');

// Trivia
out.push('insert into public.trivia_questions (id, prompt, actor_id, choices, answer_index, fact, position) values');
out.push(realTrivia.map((t, i) =>
  `  (${q(t.id)}, ${q(t.prompt)}, ${q(t.actorId)}, ${arr(t.choices)}, ${t.answerIndex}, ${q(t.fact)}, ${i})`,
).join(',\n') + '\non conflict (id) do nothing;\n');

out.push('commit;');
writeFileSync('supabase/seed.sql', out.join('\n') + '\n');

// Manifest for the art generator (posters + feature banners; actors use real photos)
writeFileSync('supabase/scripts/art-manifest.json', JSON.stringify({
  actors: [],
  titles: [...titles].map(([id, t]) => ({ id, ...t })),
  news: realFeatures.map((n) => ({ id: n.id, tag: n.tag, headline: n.headline })),
}, null, 2));

console.log(`seed.sql: ${realActors.length} actors, ${titles.size} titles, ${realFeatures.length} features, ${realTrivia.length} trivia`);
