// Seed data for real Filipino actors. Every fact here was checked against the actor's English
// Wikipedia article (or the linked filmography/awards lists and film articles) in September 2026.
// Photos come from Wikimedia Commons — see photo-credits.json. Bios are short paraphrases, not copies.
// Keep it factual: no invented awards, quotes, follower counts or social handles.

export type Network = 'ABS-CBN' | 'GMA' | 'Viva' | 'TV5' | 'Independent';
export type CreditType = 'Movie' | 'Teleserye' | 'Series';

export interface RealActor {
  id: string;
  name: string;
  stageName: string;
  tagline: string;
  birthdate: string; // ISO
  hometown: string; // birthplace per the Wikipedia infobox
  network: Network;
  agency: string;
  generation: 'Legends' | 'Millennial' | 'Gen Z';
  gender: 'Female' | 'Male';
  decades: string[];
  genres: string[];
  bio: string;
  credits: { title: string; year: number; type: CreditType; role: string }[];
  awards: { title: string; org: string; year: number; won: boolean }[];
}

const D80 = ['1980s', '1990s', '2000s', '2010s', '2020s'];

export const realActors: RealActor[] = [
  {
    id: 'vilma-santos',
    name: 'Vilma Santos',
    stageName: '',
    tagline: 'Child star turned box-office queen, and Governor of Batangas',
    birthdate: '1953-11-03',
    hometown: 'Manila',
    network: 'Independent',
    agency: '',
    generation: 'Legends',
    gender: 'Female',
    decades: D80,
    genres: ['Drama', 'Period'],
    bio: 'Vilma Santos began acting as a child in the 1960s and became one of the biggest box-office draws of the 1970s and early 1980s. Her honors include thirteen FAMAS Awards, eleven Gawad Urian and five Luna Awards, for films such as Relasyon, Sister Stella L. and Dekada \'70. Alongside acting she built a long career in public service: Mayor of Lipa (1998–2007), Governor of Batangas (2007–2016), representative of Batangas\' 6th district (2016–2022) and, since 2025, Governor of Batangas once more.',
    credits: [
      { title: 'Relasyon', year: 1982, type: 'Movie', role: 'Marilou Castañeda' },
      { title: 'Sister Stella L.', year: 1984, type: 'Movie', role: 'Sister Stella Legaspi' },
      { title: "Dekada '70", year: 2002, type: 'Movie', role: 'Amanda Bartolome' },
      { title: 'Uninvited', year: 2024, type: 'Movie', role: 'Lilia Capistrano / Eva Candelaria' },
    ],
    awards: [
      { title: 'Best Actress · Dama de Noche', org: 'FAMAS Awards', year: 1972, won: true },
      { title: 'Best Actress · Burlesk Queen', org: 'Metro Manila Film Festival', year: 1977, won: true },
      { title: 'Best Actress · Sister Stella L.', org: 'Gawad Urian', year: 1984, won: true },
    ],
  },
  {
    id: 'sharon-cuneta',
    name: 'Sharon Cuneta',
    stageName: 'Megastar',
    tagline: 'The Megastar: million-selling singer and blockbuster leading lady',
    birthdate: '1966-01-06',
    hometown: 'Santa Mesa, Manila',
    network: 'ABS-CBN',
    agency: '',
    generation: 'Legends',
    gender: 'Female',
    decades: D80,
    genres: ['Drama', 'Romance', 'Comedy'],
    bio: 'Sharon Cuneta rose to fame as a recording artist with the 1978 single "Tawag ng Pag-ibig" and the hit "Mr. DJ", and is one of the best-selling Filipino musicians of all time. She made her film debut opposite Gabby Concepcion in Dear Heart (1981), followed by blockbusters such as Bituing Walang Ningning (1985), Madrasta (1996) and Crying Ladies (2003). Her accolades include three FAMAS Awards, a Gawad Urian and nineteen Box Office Entertainment Awards.',
    credits: [
      { title: 'Dear Heart', year: 1981, type: 'Movie', role: 'April' },
      { title: 'Bituing Walang Ningning', year: 1985, type: 'Movie', role: 'Dorina Pineda' },
      { title: 'Caregiver', year: 2008, type: 'Movie', role: 'Sarah Gonzales' },
      { title: "FPJ's Ang Probinsyano", year: 2015, type: 'Teleserye', role: 'Aurora Guillermo-Hidalgo' },
    ],
    awards: [
      { title: 'Box Office Queen · Madrasta', org: 'Box Office Entertainment Awards', year: 1997, won: true },
      { title: 'Best Actress · Crying Ladies', org: 'Brussels International Film Festival', year: 2004, won: true },
      { title: "Best Actress · Mano Po 6: A Mother's Love", org: 'Metro Manila Film Festival', year: 2009, won: true },
    ],
  },
  {
    id: 'christopher-de-leon',
    name: 'Christopher de Leon',
    stageName: 'Boyet',
    tagline: 'The King of Philippine Drama, a leading man for five decades',
    birthdate: '1956-10-31',
    hometown: 'Manila',
    network: 'Independent',
    agency: '',
    generation: 'Legends',
    gender: 'Male',
    decades: D80,
    genres: ['Drama', 'Period', 'Romance'],
    bio: 'Christopher de Leon won the FAMAS Award for Best Actor for his very first film, Lino Brocka\'s Tinimbang Ka Ngunit Kulang (1974), and a second for Eddie Romero\'s Ganito Kami Noon... Paano Kayo Ngayon? (1976). Often called the "King of Philippine Drama", he has led period, romance and thriller productions for more than five decades, from Ikaw ay Akin (1978) to Dekada \'70 (2002). He is in the Best Actor Hall of Fame of both the FAMAS Awards (1993) and the Metro Manila Film Festival (2019).',
    credits: [
      { title: 'Tinimbang Ka Ngunit Kulang', year: 1974, type: 'Movie', role: 'Junior Blanco' },
      { title: 'Ganito Kami Noon... Paano Kayo Ngayon?', year: 1976, type: 'Movie', role: 'Kulas' },
      { title: 'Ikaw ay Akin', year: 1978, type: 'Movie', role: 'Rex Aguilar' },
      { title: "Dekada '70", year: 2002, type: 'Movie', role: 'Julián Bartolome Sr.' },
    ],
    awards: [
      { title: 'Best Actor · Tinimbang Ka Ngunit Kulang', org: 'FAMAS Awards', year: 1975, won: true },
      { title: 'Best Actor · Ganito Kami Noon... Paano Kayo Ngayon?', org: 'Metro Manila Film Festival', year: 1976, won: true },
      { title: 'Best Actor · My Other Woman', org: 'Gawad Urian', year: 1991, won: true },
    ],
  },
  {
    id: 'maricel-soriano',
    name: 'Maricel Soriano',
    stageName: 'The Diamond Star',
    tagline: 'The Diamond Star, from child actress to drama and comedy icon',
    birthdate: '1965-02-25',
    hometown: 'Pasay',
    network: 'Independent',
    agency: '',
    generation: 'Legends',
    gender: 'Female',
    decades: D80,
    genres: ['Drama', 'Comedy'],
    bio: 'Maricel Soriano debuted as a child in My Heart Belongs to Daddy (1971) and played Shirley Puruntong in John en Marsha, the longest-running Philippine sitcom. Launched as one of the first Regal Babies, she headlined 1980s hits such as Inday Bote (1985) and kept television audiences through her weekly drama anthologies. Known as "The Diamond Star", she has won two Asian Television Awards, five FAMAS Awards and four Luna Awards.',
    credits: [
      { title: 'John en Marsha', year: 1973, type: 'Series', role: 'Shirley Puruntong' },
      { title: 'Inday Bote', year: 1985, type: 'Movie', role: 'Inday Vargas' },
      { title: 'Florinda', year: 2009, type: 'Teleserye', role: 'Florinda Arguelles' },
      { title: "The General's Daughter", year: 2019, type: 'Teleserye', role: 'Isabelle "Nanang Sabel" Sarmiento' },
    ],
    awards: [
      { title: 'Best Actress · Inang Yaya', org: 'FAMAS Awards', year: 2007, won: true },
      { title: 'Best Drama Actress · Florinda', org: 'PMPC Star Awards for Television', year: 2010, won: true },
      { title: 'Hall of Fame', org: 'Metro Manila Film Festival', year: 2019, won: true },
    ],
  },
  {
    id: 'piolo-pascual',
    name: 'Piolo Pascual',
    stageName: 'Papa P',
    tagline: 'Heartthrob, action star and the producer behind Kita Kita',
    birthdate: '1977-01-12',
    hometown: 'Manila',
    network: 'ABS-CBN',
    agency: '',
    generation: 'Millennial',
    gender: 'Male',
    decades: ['1990s', '2000s', '2010s', '2020s'],
    genres: ['Drama', 'Romance', 'Action', 'Fantasy'],
    bio: 'Piolo Pascual got his start with a bit part in The Vizconde Massacre Story (1993) and on the youth variety show That\'s Entertainment, then rose to fame opposite Judy Ann Santos in the 1997 soap opera Esperanza. His turn in the period film Dekada \'70 (2002) won Best Supporting Actor at the FAMAS, Gawad Urian and PMPC Star Awards. He top-billed the supernatural series Lobo (2008), starred in the Cannes-screened thriller On the Job (2013), and produced the Kimmy Dora films and Kita Kita (2017).',
    credits: [
      { title: 'Esperanza', year: 1997, type: 'Teleserye', role: 'Brian' },
      { title: "Dekada '70", year: 2002, type: 'Movie', role: 'Julian "Jules" Bartolome Jr.' },
      { title: 'Lobo', year: 2008, type: 'Teleserye', role: 'Noah Ortega' },
      { title: 'On the Job', year: 2013, type: 'Movie', role: 'Francis Coronel Jr.' },
    ],
    awards: [
      { title: "Best Supporting Actor · Dekada '70", org: 'FAMAS Awards', year: 2003, won: true },
      { title: "Best Supporting Actor · Dekada '70", org: 'Gawad Urian', year: 2003, won: true },
      { title: "Best Supporting Actor · Dekada '70", org: 'PMPC Star Awards for Movies', year: 2003, won: true },
    ],
  },
  {
    id: 'coco-martin',
    name: 'Coco Martin',
    stageName: 'Ultimate Superstar',
    tagline: "From indie breakout to the star of FPJ's Ang Probinsyano",
    birthdate: '1981-11-01',
    hometown: 'Santa Cruz, Manila',
    network: 'ABS-CBN',
    agency: '',
    generation: 'Millennial',
    gender: 'Male',
    decades: ['2000s', '2010s', '2020s'],
    genres: ['Action', 'Drama', 'Fantasy'],
    bio: "Coco Martin broke through in acclaimed independent films such as Serbis, Kinatay and Jay, winning Best Supporting Actor at the Gawad Urian for the last. He moved into primetime with Tayong Dalawa (2009) and Juan dela Cruz (2013), then became a superstar as Cardo Dalisay in FPJ's Ang Probinsyano (2015–2022), the second longest-running drama series on Philippine television, followed by FPJ's Batang Quiapo (2023). Named Actor of the Decade (2000–2009) at the Gawad Urian, he also directs and produces through CCM Film Productions.",
    credits: [
      { title: 'Jay', year: 2008, type: 'Movie', role: 'Edward Navarro' },
      { title: 'Juan dela Cruz', year: 2013, type: 'Teleserye', role: 'Juan dela Cruz' },
      { title: "FPJ's Ang Probinsyano", year: 2015, type: 'Teleserye', role: 'Ricardo "Cardo" Dalisay' },
      { title: "FPJ's Batang Quiapo", year: 2023, type: 'Teleserye', role: 'Tanggol' },
    ],
    awards: [
      { title: 'Best Supporting Actor · Jay', org: 'Gawad Urian', year: 2009, won: true },
      { title: 'Actor of the Decade (2000–2009)', org: 'Gawad Urian', year: 2011, won: true },
      { title: "Best Drama Actor · FPJ's Ang Probinsyano", org: 'PMPC Star Awards for Television', year: 2016, won: true },
    ],
  },
  {
    id: 'marian-rivera',
    name: 'Marian Rivera',
    stageName: 'Primetime Queen',
    tagline: 'Kapuso Primetime Queen, from Marimar to Best Actress for Balota',
    birthdate: '1984-08-12',
    hometown: 'Madrid, Spain',
    network: 'GMA',
    agency: '',
    generation: 'Millennial',
    gender: 'Female',
    decades: ['2000s', '2010s', '2020s'],
    genres: ['Drama', 'Romance', 'Fantasy'],
    bio: 'Born in Madrid, Marian Rivera began as a commercial model and made her film debut in Enteng Kabisote 2 (2005). She rose to stardom in the 2007 remake of Marimar, then led fantasy and drama hits such as Dyesebel (2008), Darna (2009) and Amaya (2011). Her films as a lead have grossed more than ₱1.9 billion, and her role as a teacher in the political thriller Balota (2024) won Best Actress at Cinemalaya and the FAMAS Awards.',
    credits: [
      { title: 'Marimar', year: 2007, type: 'Teleserye', role: 'Marimar Perez-Santibañez' },
      { title: 'Dyesebel', year: 2008, type: 'Teleserye', role: 'Dyesebel' },
      { title: 'Amaya', year: 2011, type: 'Teleserye', role: 'Bai Amaya' },
      { title: 'Balota', year: 2024, type: 'Movie', role: 'Emmy' },
    ],
    awards: [
      { title: 'Best Drama Actress · Temptation of Wife', org: 'PMPC Star Awards for Television', year: 2013, won: true },
      { title: 'Best Actress · Balota', org: 'Cinemalaya Independent Film Festival', year: 2024, won: true },
      { title: 'Best Actress · Balota', org: 'FAMAS Awards', year: 2025, won: true },
    ],
  },
  {
    id: 'dingdong-dantes',
    name: 'Dingdong Dantes',
    stageName: '',
    tagline: 'Leading man, Family Feud host and producer of Rewind',
    birthdate: '1980-08-02',
    hometown: 'Quezon City',
    network: 'GMA',
    agency: '',
    generation: 'Millennial',
    gender: 'Male',
    decades: ['2000s', '2010s', '2020s'],
    genres: ['Drama', 'Romance', 'Fantasy'],
    bio: 'Dingdong Dantes gained prominence in the early 2000s in dramas such as Sana ay Ikaw na Nga (2001) and Twin Hearts (2004), and wider fame opposite Marian Rivera in Marimar (2007). He has hosted StarStruck, Family Feud and Amazing Earth, and produces films through AgostoDos Pictures, including Tiktik: The Aswang Chronicles (2012) and Rewind (2023), which became the highest-grossing film in the Philippines. He married Rivera in 2014.',
    credits: [
      { title: 'Marimar', year: 2007, type: 'Teleserye', role: 'Sergio Santibañez' },
      { title: 'Stairway to Heaven', year: 2009, type: 'Teleserye', role: 'Pocholo "Cholo" Fuentebella' },
      { title: 'Rewind', year: 2023, type: 'Movie', role: 'John Nuñez' },
    ],
    awards: [
      { title: 'Best Drama Actor · Stairway to Heaven', org: 'PMPC Star Awards for Television', year: 2010, won: true },
      { title: 'Best Actor · One More Try', org: 'Metro Manila Film Festival', year: 2012, won: true },
    ],
  },
  {
    id: 'anne-curtis',
    name: 'Anne Curtis',
    stageName: '',
    tagline: "Actress, It's Showtime host and UNICEF national ambassador",
    birthdate: '1985-02-17',
    hometown: 'Yarrawonga, Victoria, Australia',
    network: 'Viva',
    agency: 'Viva Artists Agency',
    generation: 'Millennial',
    gender: 'Female',
    decades: ['1990s', '2000s', '2010s', '2020s'],
    genres: ['Drama', 'Romance', 'Comedy'],
    bio: "Anne Curtis made her film debut at twelve in Magic Kingdom: Ang Alamat ng Damortis (1997) and broke through as a disfigured woman in Kampanerang Kuba (2005). She won the Metro Manila Film Festival Best Actress award for Baler (2008) and the FAMAS Best Actress award for No Other Woman (2011), which became the highest-grossing Filipino film at the time. A co-host of It's Showtime since 2009, she has served as UNICEF's national ambassador in the Philippines since 2019.",
    credits: [
      { title: 'Kampanerang Kuba', year: 2005, type: 'Teleserye', role: 'Fatima "Imang" de Vera' },
      { title: 'Baler', year: 2008, type: 'Movie', role: 'Feliza Reyes' },
      { title: 'No Other Woman', year: 2011, type: 'Movie', role: 'Kara Zalderiaga' },
    ],
    awards: [
      { title: 'Best Actress · Baler', org: 'Metro Manila Film Festival', year: 2008, won: true },
      { title: 'Best Supporting Actress · In Your Eyes', org: 'Luna Awards', year: 2011, won: true },
    ],
  },
  {
    id: 'kathryn-bernardo',
    name: 'Kathryn Bernardo',
    stageName: '',
    tagline: 'Star of three of the highest-grossing Filipino films ever',
    birthdate: '1996-03-26',
    hometown: 'Cabanatuan, Nueva Ecija',
    network: 'ABS-CBN',
    agency: 'Star Magic',
    generation: 'Millennial',
    gender: 'Female',
    decades: ['2000s', '2010s', '2020s'],
    genres: ['Drama', 'Romance', 'Comedy'],
    bio: 'Born in Cabanatuan, Kathryn Bernardo began as a child actress and rose to prominence as one of the title characters in Mara Clara (2010). Princess and I (2012) began her long screen partnership with Daniel Padilla. She has starred in three of the highest-grossing Filipino films of all time, The Hows of Us (2018), Hello, Love, Goodbye (2019) and Hello, Love, Again (2024), and won the FAMAS Award for Best Actress for the black comedy A Very Good Girl (2023).',
    credits: [
      { title: 'Mara Clara', year: 2010, type: 'Teleserye', role: 'Mara David' },
      { title: 'Princess and I', year: 2012, type: 'Teleserye', role: 'Mikay Maghirang / Princess Areeyah' },
      { title: 'The Hows of Us', year: 2018, type: 'Movie', role: 'Georgina "George" Reyes' },
      { title: 'Hello, Love, Goodbye', year: 2019, type: 'Movie', role: 'Joy Fabregas' },
      { title: 'A Very Good Girl', year: 2023, type: 'Movie', role: 'Philomena "Philo" Angeles' },
    ],
    awards: [
      { title: 'Movie Actress of the Year · The Hows of Us', org: 'PMPC Star Awards for Movies', year: 2019, won: true },
      { title: 'Best Actress · A Very Good Girl', org: 'FAMAS Awards', year: 2024, won: true },
      { title: 'Best Actress in a Leading Role · A Very Good Girl', org: 'Asian Academy Creative Awards', year: 2024, won: true },
    ],
  },
  {
    id: 'daniel-padilla',
    name: 'Daniel Padilla',
    stageName: '',
    tagline: 'Singer-actor behind Barcelona and The Hows of Us',
    birthdate: '1995-04-26',
    hometown: 'Manila',
    network: 'ABS-CBN',
    agency: 'Star Magic',
    generation: 'Millennial',
    gender: 'Male',
    decades: ['2010s', '2020s'],
    genres: ['Romance', 'Drama', 'Fantasy'],
    bio: "Daniel Padilla debuted in the soap opera Gimik 2010 (2010) and landed his first lead in Growing Up (2011). With Kathryn Bernardo he starred in hit series such as Princess and I, Got to Believe and La Luna Sangre, and films including She's Dating the Gangster (2014), Barcelona: A Love Untold (2016) and The Hows of Us (2018). His films have earned ₱3.14 billion at the box office, and as a singer he has released several double-platinum albums.",
    credits: [
      { title: 'Princess and I', year: 2012, type: 'Teleserye', role: 'Gino Dela Rosa' },
      { title: 'Got to Believe', year: 2013, type: 'Teleserye', role: 'Joaquin' },
      { title: 'Barcelona: A Love Untold', year: 2016, type: 'Movie', role: 'Ely Antonio' },
      { title: 'The Hows of Us', year: 2018, type: 'Movie', role: 'Primo Alvarez' },
    ],
    awards: [
      { title: 'Best Actor · Barcelona: A Love Untold', org: 'FAMAS Awards', year: 2017, won: true },
      { title: 'Movie Actor of the Year · Barcelona: A Love Untold', org: 'PMPC Star Awards for Movies', year: 2017, won: true },
      { title: 'Best Actor · The Hows of Us', org: 'Luna Awards', year: 2019, won: true },
    ],
  },
  {
    id: 'alden-richards',
    name: 'Alden Richards',
    stageName: "Asia's Multimedia Star",
    tagline: 'Kapuso leading man, from AlDub to Hello, Love, Again',
    birthdate: '1992-01-02',
    hometown: 'Quezon City',
    network: 'GMA',
    agency: 'Sparkle GMA Artist Center',
    generation: 'Millennial',
    gender: 'Male',
    decades: ['2010s', '2020s'],
    genres: ['Romance', 'Drama', 'Period', 'Action'],
    bio: 'Alden Richards made his screen debut in the fantasy series Alakdana (2011) and broke through in the romantic drama One True Love (2012). He became a phenomenon in the Kalyeserye segment opposite Maine Mendoza, known as AlDub, and went on to play José Rizal in Ilustrado (2014) and star in Pulang Araw (2024). Hello, Love, Goodbye (2019) and Hello, Love, Again (2024) rank among the highest-grossing Filipino films of all time, and he made his directing debut with Out of Order (2025).',
    credits: [
      { title: 'One True Love', year: 2012, type: 'Teleserye', role: 'Tisoy Bulaong' },
      { title: 'Ilustrado', year: 2014, type: 'Teleserye', role: 'José Rizal' },
      { title: 'Hello, Love, Goodbye', year: 2019, type: 'Movie', role: 'Ethan Del Rosario' },
      { title: 'Pulang Araw', year: 2024, type: 'Teleserye', role: 'Eduardo dela Cruz' },
    ],
    awards: [
      { title: 'Best Drama Actor · Ilustrado', org: 'PMPC Star Awards for Television', year: 2015, won: true },
      { title: 'Box Office King', org: 'Box Office Entertainment Awards', year: 2024, won: true },
    ],
  },
  {
    id: 'liza-soberano',
    name: 'Liza Soberano',
    stageName: '',
    tagline: 'Forevermore star who took her career to Hollywood',
    birthdate: '1998-01-04',
    hometown: 'Santa Clara, California, U.S.',
    network: 'Independent',
    agency: '',
    generation: 'Gen Z',
    gender: 'Female',
    decades: ['2010s', '2020s'],
    genres: ['Romance', 'Drama', 'Comedy', 'Horror'],
    bio: 'Born in Santa Clara, California, Liza Soberano moved to Quezon City and began modelling at thirteen. After her debut in the anthology Wansapanataym (2011), she broke through as the strawberry farmer Agnes in Forevermore (2014), the first of her pairings with Enrique Gil, and was named Box Office Queen for My Ex and Whys (2017). She voiced Alexandra Trese in the animated series Trese (2021) and, after returning to California, appeared in the horror comedy Lisa Frankenstein (2024).',
    credits: [
      { title: 'Forevermore', year: 2014, type: 'Teleserye', role: 'Agnes' },
      { title: 'My Ex and Whys', year: 2017, type: 'Movie', role: 'Calista "Cali" Ferrer' },
      { title: 'Trese', year: 2021, type: 'Series', role: 'Alexandra Trese (voice)' },
      { title: 'Lisa Frankenstein', year: 2024, type: 'Movie', role: 'Taffy' },
    ],
    awards: [
      { title: 'Box Office Queen · My Ex and Whys', org: 'Box Office Entertainment Awards', year: 2018, won: true },
    ],
  },
  {
    id: 'donny-pangilinan',
    name: 'Donny Pangilinan',
    stageName: '',
    tagline: "Myx VJ turned leading man of He's Into Her and Can't Buy Me Love",
    birthdate: '1998-02-10',
    hometown: 'Manila',
    network: 'ABS-CBN',
    agency: 'Star Magic',
    generation: 'Gen Z',
    gender: 'Male',
    decades: ['2010s', '2020s'],
    genres: ['Romance', 'Comedy', 'Drama'],
    bio: "Donny Pangilinan started out in 2016 as a video jockey on the music channel Myx and made his film debut in Regal Films' Walwal (2018). He has since led a string of Star Cinema productions, most notably James & Pat & Dave (2020), the series He's Into Her (2021) and the teleserye Can't Buy Me Love (2023–2024). He also records music under Universal Records.",
    credits: [
      { title: 'Walwal', year: 2018, type: 'Movie', role: 'Bobby' },
      { title: 'James & Pat & Dave', year: 2020, type: 'Movie', role: 'Dave Verona' },
      { title: "He's Into Her", year: 2021, type: 'Series', role: 'Deib Lohr Enrile' },
      { title: "Can't Buy Me Love", year: 2023, type: 'Teleserye', role: 'Andrei "Bingo" Mariano' },
    ],
    awards: [],
  },
  {
    id: 'barbie-forteza',
    name: 'Barbie Forteza',
    stageName: 'Kapuso Primetime Princess',
    tagline: 'Maria Clara at Ibarra star and Fantasporto Best Actress',
    birthdate: '1997-07-31',
    hometown: 'Biñan, Laguna',
    network: 'GMA',
    agency: 'Sparkle GMA Artist Center',
    generation: 'Gen Z',
    gender: 'Female',
    decades: ['2000s', '2010s', '2020s'],
    genres: ['Drama', 'Period', 'Romance'],
    bio: "Barbie Forteza won Best Supporting Actress at the 10th Cinemalaya festival for playing a shoemaker's daughter in Mariquina (2014), and Best Actress at Portugal's Fantasporto festival for the sea-gypsy drama Laut (2016). On television she led The Half Sisters (2014) and gained wider recognition with Maria Clara at Ibarra (2022), Maging Sino Ka Man (2023) and the war drama Pulang Araw (2024). In 2017 the National Commission for Culture and the Arts gave her an Ani ng Dangal award.",
    credits: [
      { title: 'The Half Sisters', year: 2014, type: 'Teleserye', role: 'Diana Valdicañas' },
      { title: 'Maria Clara at Ibarra', year: 2022, type: 'Teleserye', role: 'María Clara "Klay" Infantes' },
      { title: 'Pulang Araw', year: 2024, type: 'Teleserye', role: 'Adelina "Chinita" dela Cruz' },
    ],
    awards: [
      { title: 'Best Supporting Actress · Mariquina', org: 'Cinemalaya Independent Film Festival', year: 2014, won: true },
      { title: 'Best Actress · Laut', org: 'Fantasporto International Film Festival', year: 2016, won: true },
    ],
  },
  {
    id: 'maris-racal',
    name: 'Maris Racal',
    stageName: '',
    tagline: "Pinoy Big Brother runner-up turned breakout star of Can't Buy Me Love",
    birthdate: '1997-09-22',
    hometown: 'Tagum, Davao del Norte',
    network: 'ABS-CBN',
    agency: '',
    generation: 'Gen Z',
    gender: 'Female',
    decades: ['2010s', '2020s'],
    genres: ['Drama', 'Romance', 'Action'],
    bio: "Maris Racal rose to prominence in 2014 as runner-up of Pinoy Big Brother: All In, then signed with Star Magic and performed with the dance groups Girltrends and BFF5. Her breakthrough came as Irene Tiu in the ABS-CBN romantic drama Can't Buy Me Love (2023–2024). She led the drama Sunshine (2024), an entry at the 49th Toronto International Film Festival, and joined the action drama series Incognito (2025).",
    credits: [
      { title: "Can't Buy Me Love", year: 2023, type: 'Teleserye', role: 'Irene Tiu' },
      { title: 'Sunshine', year: 2024, type: 'Movie', role: 'Sunshine Francisco' },
      { title: 'Incognito', year: 2025, type: 'Teleserye', role: 'Gabriela "Gab" Rivera-Guerrero' },
    ],
    awards: [],
  },
];

export const realSpotlight = ['kathryn-bernardo', 'coco-martin', 'marian-rivera', 'vilma-santos', 'alden-richards'];
export const realTrending = [
  'kathryn-bernardo', 'alden-richards', 'coco-martin', 'marian-rivera', 'maris-racal', 'donny-pangilinan',
  'dingdong-dantes', 'anne-curtis', 'daniel-padilla', 'barbie-forteza', 'vilma-santos', 'sharon-cuneta',
];

// Features, not news: evergreen stories built only from the facts above (no invented events).
export const realFeatures = [
  {
    id: 'f1', tag: 'Box Office', minutesRead: 3, ago: '2 hours', actorId: 'kathryn-bernardo',
    headline: 'The Hello, Love films and the record books',
    excerpt: 'Kathryn Bernardo and Alden Richards share two of the highest-grossing Filipino films of all time.',
    body: 'Hello, Love, Goodbye (2019) paired ABS-CBN\'s Kathryn Bernardo with GMA\'s Alden Richards, stars from rival networks, as a domestic worker and a bartender in Hong Kong. Five years later Hello, Love, Again (2024) reunited them, and both films now rank among the highest-grossing Filipino films ever made.\n\nFor Bernardo that makes three all-time box-office hits, counting The Hows of Us (2018) with Daniel Padilla. Richards, meanwhile, went on to make his directing debut with the legal thriller Out of Order (2025).',
  },
  {
    id: 'f2', tag: 'Legends', minutesRead: 4, ago: '6 hours', actorId: 'christopher-de-leon',
    headline: "One family, three stars: Dekada '70",
    excerpt: "Vilma Santos, Christopher de Leon and Piolo Pascual all share one family in Chito S. Roño's 2002 drama.",
    body: "Dekada '70 (2002) follows the Bartolome family through the 1970s. Vilma Santos plays the mother, Amanda; Christopher de Leon is the father, Julián; and Piolo Pascual plays their eldest son, Jules.\n\nThe film is adapted from Lualhati Bautista's 1983 novel, and Pascual's performance earned him Best Supporting Actor at the FAMAS, Gawad Urian and PMPC Star Awards in 2003.",
  },
  {
    id: 'f3', tag: 'Teleserye', minutesRead: 3, ago: '1 day', actorId: 'coco-martin',
    headline: "Cardo Dalisay's seven-year run",
    excerpt: "FPJ's Ang Probinsyano aired from 2015 to 2022, one of the longest-running dramas on Philippine TV.",
    body: "Coco Martin played police officer Cardo Dalisay in FPJ's Ang Probinsyano from 2015 to 2022, making it the second longest-running drama series on Philippine television. Sharon Cuneta joined the cast in its later seasons as First Lady Aurora Guillermo-Hidalgo.\n\nMartin followed it with FPJ's Batang Quiapo in 2023, where he plays Tanggol.",
  },
  {
    id: 'f4', tag: 'Awards', minutesRead: 2, ago: '2 days', actorId: 'marian-rivera',
    headline: "Marian Rivera's Balota sweep",
    excerpt: 'Her turn as a teacher in the political thriller won Best Actress at Cinemalaya and the FAMAS Awards.',
    body: "Marian Rivera, best known as the Kapuso \"Primetime Queen\" of fantasy hits like Marimar and Dyesebel, took a very different role in Kip Oebanda's political thriller Balota (2024). Playing Emmy, a teacher thrust into danger, she won Best Actress at the 20th Cinemalaya festival and later at the FAMAS Awards.",
  },
  {
    id: 'f5', tag: 'New Gen', minutesRead: 3, ago: '3 days', actorId: 'maris-racal',
    headline: "The Can't Buy Me Love class",
    excerpt: 'Donny Pangilinan and Maris Racal both found big roles in the 2023–2024 ABS-CBN drama.',
    body: "Can't Buy Me Love (2023–2024) gave Donny Pangilinan the role of Andrei \"Bingo\" Mariano, and Maris Racal her breakthrough as Irene Tiu. Racal went on to lead Sunshine (2024), shown at the 49th Toronto International Film Festival, and joined the action drama series Incognito in 2025.",
  },
  {
    id: 'f6', tag: 'Legends', minutesRead: 3, ago: '3 days', actorId: 'sharon-cuneta',
    headline: 'From "Mr. DJ" to Megastar',
    excerpt: 'Sharon Cuneta was a chart-topping singer before she became one of the biggest film stars of the 1980s.',
    body: 'Sharon Cuneta released her first single, "Tawag ng Pag-ibig", in 1978 and broke out with "Mr. DJ". Her film debut, Dear Heart (1981), started a run of hits including Bituing Walang Ningning (1985) and Madrasta (1996). In 2004 she won Best Actress at the Brussels International Film Festival for Crying Ladies.',
  },
];

// Trivia rounds. The photo shown is the actor's own (actor_id), so questions describe them.
export const realTrivia = [
  { id: 't1', actorId: 'coco-martin', prompt: "He played Cardo Dalisay for seven years in FPJ's Ang Probinsyano. Who is he?", choices: ['Coco Martin', 'Piolo Pascual', 'Dingdong Dantes', 'Daniel Padilla'], answerIndex: 0, fact: "Coco Martin's real name is Rodel Nacianceno." },
  { id: 't2', actorId: 'kathryn-bernardo', prompt: 'She won FAMAS Best Actress for A Very Good Girl. Name her.', choices: ['Liza Soberano', 'Kathryn Bernardo', 'Barbie Forteza', 'Maris Racal'], answerIndex: 1, fact: 'Kathryn Bernardo was born in Cabanatuan, Nueva Ecija.' },
  { id: 't3', actorId: 'marian-rivera', prompt: 'This Primetime Queen was born in Madrid. Who is she?', choices: ['Anne Curtis', 'Marian Rivera', 'Maricel Soriano', 'Sharon Cuneta'], answerIndex: 1, fact: 'Marian Rivera rose to stardom in the 2007 remake of Marimar.' },
  { id: 't4', actorId: 'vilma-santos', prompt: 'Actress, and Governor of Batangas. Who is she?', choices: ['Sharon Cuneta', 'Maricel Soriano', 'Vilma Santos', 'Barbie Forteza'], answerIndex: 2, fact: 'Vilma Santos has won thirteen FAMAS Awards and eleven Gawad Urian.' },
  { id: 't5', actorId: 'christopher-de-leon', prompt: 'He won FAMAS Best Actor for his very first film in 1974. Name him.', choices: ['Piolo Pascual', 'Christopher de Leon', 'Coco Martin', 'Alden Richards'], answerIndex: 1, fact: 'His debut was Lino Brocka\'s Tinimbang Ka Ngunit Kulang.' },
  { id: 't6', actorId: 'alden-richards', prompt: 'He played José Rizal in Ilustrado. Who is he?', choices: ['Dingdong Dantes', 'Donny Pangilinan', 'Alden Richards', 'Daniel Padilla'], answerIndex: 2, fact: "Alden Richards is known as Asia's Multimedia Star." },
  { id: 't7', actorId: 'sharon-cuneta', prompt: 'The "Megastar" who first hit it big with "Mr. DJ". Name her.', choices: ['Sharon Cuneta', 'Vilma Santos', 'Anne Curtis', 'Maricel Soriano'], answerIndex: 0, fact: 'Her film debut was Dear Heart (1981).' },
  { id: 't8', actorId: 'anne-curtis', prompt: "She won MMFF Best Actress for Baler and co-hosts It's Showtime. Who is she?", choices: ['Marian Rivera', 'Liza Soberano', 'Kathryn Bernardo', 'Anne Curtis'], answerIndex: 3, fact: 'Anne Curtis was born in Victoria, Australia.' },
  { id: 't9', actorId: 'maricel-soriano', prompt: 'The Diamond Star played Shirley Puruntong in John en Marsha. Name her.', choices: ['Maricel Soriano', 'Vilma Santos', 'Sharon Cuneta', 'Marian Rivera'], answerIndex: 0, fact: 'John en Marsha is the longest-running Philippine sitcom.' },
  { id: 't10', actorId: 'barbie-forteza', prompt: 'She played María Clara "Klay" in Maria Clara at Ibarra. Who is she?', choices: ['Maris Racal', 'Barbie Forteza', 'Kathryn Bernardo', 'Liza Soberano'], answerIndex: 1, fact: 'She won Best Actress at Portugal\'s Fantasporto festival for Laut.' },
  { id: 't11', actorId: 'piolo-pascual', prompt: 'He rose to fame in Esperanza and later produced Kita Kita. Name him.', choices: ['Christopher de Leon', 'Coco Martin', 'Piolo Pascual', 'Dingdong Dantes'], answerIndex: 2, fact: 'Piolo Pascual starred in On the Job, which screened at Cannes.' },
  { id: 't12', actorId: 'liza-soberano', prompt: 'She played Agnes in Forevermore and Taffy in Lisa Frankenstein. Who is she?', choices: ['Liza Soberano', 'Anne Curtis', 'Barbie Forteza', 'Maris Racal'], answerIndex: 0, fact: 'Liza Soberano was born in Santa Clara, California.' },
];
